inherit_from: .rubocop_todo.yml

# .rubocop.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-capybara

# Additional configuration for Rubocop and its extensions
AllCops:
  NewCops: enable
  SuggestExtensions: false

# Example configuration for Rails cops
Rails:
  Enabled: true

# Example configuration for RSpec cops
RSpec:
  Enabled: true

# Example configuration for FactoryBot cops
FactoryBot:
  Enabled: true

# Example configuration for Capybara cops
Capybara:
  Enabled: true